CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER ROLE postgres WITH REPLICATION;

CREATE PUBLICATION users_pub FOR TABLE users;
